### ISSUE TITLE
`v10` Roadmap

### ISSUE THREAD

**Issue by hakimio** [hakimio/ngx-ui-tour#92]
Currently planned for `v10`

- [x] #91
- [x] Provide all services in `root` and remove `TourModule.forRoot()`
- [x] Drop support for `RxJS v6`
- [x] #85
- [x] #96 
- [x] All directives and components provided as `standalone`
- [x] New tour UI: [ion-popover](https://ionicframework.com/docs/api/popover)
- [x] #99 
- [x] #100

Hopefully it will be released sometime in January 2023.

**Comment by mivanyna** [comment]
Maybe one more thing that would be good to have is some configurable space between the anchor element and backdrop(between border and backdrop in this case):
![image](https://user-images.githubusercontent.com/10868397/208633309-303acb9d-4058-46c6-a202-7e6e755ca11d.png)

**Comment by hakimio** [comment]
@mivanyna please create a separate issue for your feature request.

**Comment by hakimio** [comment]
`v10` has now been released. Check out [the release announcement](https://github.com/hakimio/ngx-ui-tour/releases/tag/v10.0.0) for more info.
